
  name: hnterm
  version: '0.2'
  summary: Hacker News in the terminal
  description: |
    Interactive browsing of Hacker News in the terminal.
  license: MIT

  base: core18
  grade: stable
  confinement: strict

  parts:
    hnterm:
      source: https://github.com/ggerganov/hnterm
      source-type: git
      plugin: cmake
      build-packages:
        - g++
        - make
        - libncurses5-dev
        - libcurl4-openssl-dev
      stage-packages:
        - libncurses5
        - libcurl4
        - xdg-utils

  apps:
    hnterm:
      command: bin/hnterm
      plugs:
        - network
        - home
        - desktop
